documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', '**/*.md']

github_actions:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', 'action.yml', 'entrypoint.sh']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['go.mod']
