name: "Carbon Guard"
description: "Estimate CI runtime carbon emissions"
author: "chenzhuyu2004"

inputs:
  duration:
    description: "Duration in seconds (optional)"
    required: false

outputs:
  emissions_kg:
    description: "Estimated emissions in kg CO2"

runs:
  using: "docker"
  image: "Dockerfile"
