name: Carbon Baseline and PR Comment

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  carbon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Record start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Carbon Guard
        id: carbon
        uses: czy/carbon-guard@v1
        with:
          start_time: ${{ env.START_TIME }}
          budget_kg: "0.0150"
          baseline_kg: "0.0164"
          fail_on_budget: "false"

      - name: Comment report
        uses: actions/github-script@v7
        with:
          script: |
            const marker = '<!-- carbon-guard-report -->';
            const emissions = '${{ steps.carbon.outputs.emissions_kg }}';
            const exceeded = '${{ steps.carbon.outputs.budget_exceeded }}';
            const delta = '${{ steps.carbon.outputs.delta_vs_baseline_pct }}';
            const body = `${marker}\n## Carbon Guard Report\n\n- Emissions: \`${emissions} kgCO2\`\n- Budget exceeded: \`${exceeded}\`\n- Delta vs baseline: \`${delta}%\``;
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const comments = await github.paginate(github.rest.issues.listComments, { owner, repo, issue_number, per_page: 100 });
            const existing = comments.find(c => c.user?.type === 'Bot' && c.body?.includes(marker));
            if (existing) {
              await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
            } else {
              await github.rest.issues.createComment({ owner, repo, issue_number, body });
            }
