name: Bug Report
description: Report a reproducible problem in Carbon Guard
title: "bug: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide enough detail to reproduce it.
  - type: input
    id: version
    attributes:
      label: Version
      description: Git tag/commit/branch (for example v1 or main)
      placeholder: v1
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command
      description: Exact command that failed
      placeholder: carbon-guard run --duration 300 --json
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste terminal output or workflow links/logs
      render: shell
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Go version, GitHub Actions runner if applicable
    validations:
      required: false
