name: Feature Request
description: Suggest an improvement to Carbon Guard
title: "feat: "
labels:
  - enhancement
body:
  - type: input
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: We need to fail CI when emissions regress over baseline.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: Describe the API/CLI/workflow changes you want
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: false
  - type: textarea
    id: impact
    attributes:
      label: Adoption Impact
      description: Why would this help teams adopt Carbon Guard?
    validations:
      required: false
